language: php

php:

- 7.2

install:

- composer self-update && composer update

script:

- phpunit

addons:
  code_climate:
    repo_token:
      secure: "I5wTvVJCAuYSGStiQ60KcMNqy10lNVNHyrPGvON1t32hcQOiFWiRmy5jEcUvHcnd4kLf4WpVVbX4g+/7JKOIGTNVi8cVkQknvWvot0mXbFaX2cdtaVNMV2SzOVijRUMCBLi454aLeWwNxzES4QvMocADcy97PA6DaeSqBRxhrzfkYp9iNs8VoL0SLAAH2YTq7BIVtnKVrba9j/pjvrKyJmtsoIBuu8rxmI3guGT+027YM6WFOPnR3JYFLXWgeEGrJFfbklRIzNUzYcAq3Nqt0UpNmaZxVu5ukj74nRz+fJcLG2O5oHjnQfSwS0sIKYsm8owb7BWCQz/kNllFhoy8Zs4XJ1V9aa46bnEuHQAkRb4GQtQ2y5SvSyQGJJwu3jiVPEPFJ5WqjAMuuTei0lPzFGyyEeuIycsWhUnUHwPDwcorJH973UD5DAzIi2wU4q/P0AkH8IuvAYVppt3vROPBMTniNHidV0cBRMCVGMLnp4UxhQP9tirIIYbUEHUV2hobb+6xFhf6e7YbZSdZfQJ1aRGA8E5WE44Obqm+9XKGZR5HVsx5z7I7RpHYRm7ZKxE3nwqU/U3dk1CXLF1VNGjgqcb2RRqbGPL8SiNb6/kSkx+oOd7TweZqPCFjgqRlpM1p3QyZ6RLPi5Aco3jC3t5YbcP/a0RAso0XqKsZzbbUlkI="

after_script:
- vendor/bin/test-reporter
